
**Creating numpy arrays**


In [85]:

# Creating an integer array with explicit dtype, which is not necessary.
import numpy as murugan
int_array = murugan.array([1, 2, 3], dtype=murugan.int32)
int_array


array([1, 2, 3], dtype=int32)

In [87]:

# Creating a 3D array (Tensor) # Dimension: 3 , Shape: (2, 2, 2)
arr_3d = murugan.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [88]:

# Create an array of 10 equally spaced values from 0 to 1
linspace_arr = murugan.linspace(0, 1, 100)
linspace_arr


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [89]:

# Create an array of 5 values spaced logarithmically from 1 to 100
logspace_arr = murugan.logspace(0, 1, 50)
logspace_arr

array([ 1.        ,  1.04811313,  1.09854114,  1.1513954 ,  1.20679264,
        1.26485522,  1.32571137,  1.38949549,  1.45634848,  1.52641797,
        1.59985872,  1.67683294,  1.75751062,  1.84206997,  1.93069773,
        2.02358965,  2.12095089,  2.22299648,  2.32995181,  2.44205309,
        2.55954792,  2.6826958 ,  2.8117687 ,  2.9470517 ,  3.0888436 ,
        3.23745754,  3.39322177,  3.55648031,  3.72759372,  3.90693994,
        4.09491506,  4.29193426,  4.49843267,  4.71486636,  4.94171336,
        5.17947468,  5.42867544,  5.68986603,  5.96362332,  6.25055193,
        6.55128557,  6.86648845,  7.19685673,  7.54312006,  7.90604321,
        8.28642773,  8.68511374,  9.10298178,  9.54095476, 10.        ])

In [90]:

# Create an array of values from 0 to 9 with a step size of 2
arange_arr = murugan.arange(0, 100, 9)
arange_arr

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [91]:

# Create a 3x3 array filled with zeros
zeros_arr = murugan.zeros((5, 5, 5))
zeros_arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [92]:

# Create a 2x4 array filled with ones
ones_arr = murugan.ones((5, 8))
ones_arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [93]:

# Create a new array filled with zeros,
# matching the shape and data type of the original array
original_array = murugan.array([1, 2, 3,4,5], dtype=murugan.int32)
zeros_array = murugan.zeros_like(original_array)
arr = zeros_array

print(arr)


[0 0 0 0 0]


In [94]:

# Create a new array filled with ones,
# matching the shape and data type of the original array
original_array = murugan.array([1, 2, 3,4,5], dtype=murugan.int32)
ones_array = murugan.ones_like(original_array)
arr = ones_array

print(arr)


[1 1 1 1 1]



**2-Array Inspection**

# Dimension and shaping

In [95]:

# Corrected 1D array creation
arr_1D = murugan.array([2, 4, 6, 8, 10, 11, 3, 6, 9, 12, 15, 18])

# Dimension: 1, shape: (12,), size: 12
print(f"Dimension: {arr_1D.ndim}, shape: {arr_1D.shape}, size: {arr_1D.size}")


Dimension: 1, shape: (12,), size: 12


**Array Indexing and Slicing**

In [96]:

# Creating a NumPy array
arr = murugan.array([101, 212, 330, 465, 579])
# Accessing individual elements
first_element = arr[0] # Access the first element (10)
print(f'First element - {first_element}')
third_element = arr[2] # Access the third element (30)
print(f'Third element - {third_element}')
# Accessing elements using negative indices
last_element = arr[-1] # Access the last element (50)
print(f'Last element - {last_element}')

First element - 101
Third element - 330
Last element - 579


In [97]:

# Creating a 2D NumPy array
arr_2d = murugan.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing along rows and columns
sliced_array = arr_2d[1,2] # Element at row 1, column 2 (value: 2)
sliced_array

6

In [98]:

# Slicing the array to create a new array
sliced_array = arr[1:4]
sliced_array

array([212, 330, 465])

In [99]:

# Slicing with a step of 2
sliced_array = arr[0::5]
sliced_array

array([101])

In [100]:

# Slicing with negative index
second_to_last = arr[-4::]
second_to_last

array([212, 330, 465, 579])

In [101]:

# Conditional slicing: Select elements greater than 30
sliced_array = arr[arr > 30]
sliced_array

array([101, 212, 330, 465, 579])

In [102]:

# Creating a 2D NumPy array
arr_2d = murugan.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slicing along rows and columns
sliced_array = arr_2d[1:3, 0:2] # Slice a 2x2 subarray: [[4, 5], [7, 8]]
sliced_array

array([[4, 5],
       [7, 8]])

**3-Array Operations 🎲**



 *Element Wise Operation*

In [103]:

# Creating 1D NumPy arrays
arr1 = murugan.array([16, 25, 13])
arr2 = murugan.array([34, 54, 16])
scalar = 2
# Addition
result_add = arr1 + arr2
result_add

array([50, 79, 29])

In [104]:

# Multiplication, Similarly subraction and division as well.
result_mul = arr1 * arr2
result_mul

array([ 544, 1350,  208])

In [105]:

# Creating 2D NumPy arrays
matrix1 = murugan.array([[1, 2, 3], [4, 5, 6]])
matrix2 = murugan.array([[55, 66, 77], [7, 8, 9]])
# Element-wise multiplication
result_mul = matrix1 * matrix2
print("Element-wise multiplication:")
print(result_mul)


Element-wise multiplication:
[[ 55 132 231]
 [ 28  40  54]]


In [106]:

# Creating 2D NumPy arrays
matrix1 = murugan.array([[1, 2, 3], [4, 5, 6]])
matrix2 = murugan.array([[55, 66, 77], [7, 8, 9]])
# Transposing matrix2 to make shapes compatible for multiplication
matrix2_transposed = matrix2.T
# Actual Matrix Multiplication using np.dot
matrix_multiplication = murugan.dot(matrix1, matrix2_transposed)
print("Actual Matrix Multiplication:")
print(matrix_multiplication)

Actual Matrix Multiplication:
[[ 418   50]
 [1012  122]]


In [107]:

# Broadcasting: Multiply array by a scalar
result = arr1 * scalar
result

array([32, 50, 26])

**Append and Delete**

In [108]:

# Create an array
original_array = murugan.array([1, 2, 3])
# Append elements in-place
original_array = murugan.append(original_array, [4, 5, 6])
original_array

array([1, 2, 3, 4, 5, 6])

In [109]:

# Create a NumPy array
arr = murugan.array([1, 2, 3, 4, 5])
# Remove the item at index 2 (value 3)
new_arr = murugan.delete(arr, 2)
new_arr

array([1, 2, 4, 5])

In [110]:

# Create a 2D NumPy array
arr = murugan.array([[1, 2, 3], [4,5, 6], [7, 8, 9]])
# Remove the second row (index 1)
new_arr = murugan.delete(arr, 1, axis=0)
new_arr

array([[1, 2, 3],
       [7, 8, 9]])

**3.3 Aggregation Functions and ufuncs**

In [111]:

# Creating a NumPy array
arr = murugan.array([1, 2, 3, 4, 5])
# Aggregation functions
mean_value = murugan.mean(arr)
print(mean_value)

3.0


In [112]:

median_value = murugan.median(arr)
variance = murugan.var(arr)
standard_deviation = murugan.std(arr)
sum_value = murugan.sum(arr)
min_value = murugan.min(arr)
max_value = murugan.max(arr)

In [113]:

# Universal functions

sqrt_arr = murugan.sqrt(arr) # Square Root
print(f'square root - {sqrt_arr}')
exp_arr = murugan.exp(arr) # Exponential
print(f'exponential array - {exp_arr}')


square root - [1.         1.41421356 1.73205081 2.         2.23606798]
exponential array - [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# Replcing Arrays

In [114]:

 # Creating 2D array

arr_2d = murugan.array([[1, 2, 3], [4, 5, 6]])
# Here as we are passing only 6, it will conver the 2d array to a 1d array
# with 6 elements, you cannot pass anything other than 6,
# as it doesn't match the original array!
arr_1d = arr_2d.reshape(6)
arr_1d

array([1, 2, 3, 4, 5, 6])

In [115]:

# Creating 1D array
arr_1d = murugan.array([1, 2, 3, 4, 5, 6])
# converting 1D array to 2D
arr_2d = arr_1d.reshape(2, 3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:

from skimage import data
# Load a sample grayscale image
image = data.coins()
# Original shape of the image
print("Original Image Shape:", image.shape) # Original Image Shape: (303, 384)
# So, if you want to convert it to 1D, you have to pass 116352 (303*384)
# Instead, if you don't want to calculate that and let numpy deal with it,
# IN such cases, you can just pass -1, and it will calculate 116352
reshaped_image = image.reshape(-1)
print("Reshapped array:", reshaped_image.shape)

Original Image Shape: (303, 384)
Reshapped array: (116352,)


**4 . Working with numpy Arrays**

# Combining Arrays

In [117]:

arr1 = murugan.array([1, 2, 3])
arr2 = murugan.array([4, 5, 6])
# Concatenate along the 0-axis (rows)
combined = murugan.concatenate((arr1, arr2)) # Result: [1, 2, 3, 4, 5, 6]
combined

array([1, 2, 3, 4, 5, 6])

In [118]:

# Vertical stacking

vertical_stack = murugan.vstack((arr1, arr2)) # Result: [[1, 2, 3], [4, 5, 6]]
vertical_stack

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:

# Horizontal stacking

horizontal_stack = murugan.hstack((arr1, arr2)) # Result: [1, 2, 3, 4, 5, 6]
horizontal_stack

array([1, 2, 3, 4, 5, 6])

# Splitting Arrays

In [120]:


arr = murugan.array([1, 2, 3, 4, 5, 6])
# Split into three equal parts
split_arr = murugan.split(arr, 3)
split_arr
# Result: [array([1, 2]), array([3, 4]), array([5, 6])].

[array([1, 2]), array([3, 4]), array([5, 6])]

In [121]:


original_arr = murugan.array([1, 2, 3])

# alias of original array
alias_arr = original_arr
# chaing a value in alias array
alias_arr[0]=10
# you can observe that it will also change the original array
original_arr

array([10,  2,  3])

In [122]:

original_arr = murugan.array([1, 2, 3])

# Changes to view_arr will affect the original array
view_arr = original_arr.view()
# Modify an element in the view
view_arr[0] = 99
# Check the original array
print(original_arr)

[99  2  3]


In [123]:

original_arr = murugan.array([1, 2, 3])

# Changes to copy_arr won't affect the original array
copy_arr = original_arr.copy()
copy_arr[0] = 100
# Copy doesn't change the original array
print(original_arr)

[1 2 3]


**Sorting Numpy Arrays**

In [124]:

data = murugan.array([3, 1, 5, 2, 4])

sorted_data = murugan.sort(data) # Ascending order
print("Ascending sort", sorted_data)
reverse_sorted_data = murugan.sort(data)[::-1] # Descending order
print("Descending sort", reverse_sorted_data)
# Returns Indices that would sort the array.
sorted_indices = murugan.argsort(data)
print("Sorted Indices", sorted_indices)

Ascending sort [1 2 3 4 5]
Descending sort [5 4 3 2 1]
Sorted Indices [1 3 0 4 2]


**5-Numpy for Data Cleaning**

# Identify Missing Values

In [125]:

# Create a NumPy array with missing values
data = murugan.array([1, 2, murugan.nan, 4, murugan.nan, 6])
# Check for missing values
has_missing = murugan.isnan(data)
print(has_missing)

[False False  True False  True False]


**Removing rows or columns with Missing Values**

In [126]:

# Create a 2D array with missing values
data = murugan.array([[1, 2, 3], [4, murugan.nan, 6], [7, 8, 9]])
# Remove rows with any missing values
cleaned_data = data[~murugan.any(murugan.isnan(data), axis=1)]
print(cleaned_data) # Result: [[1,2,3],[7,8,9]]

[[1. 2. 3.]
 [7. 8. 9.]]


**6-Numpy for Statistical Analysis**

# Data Transformation





In [127]:

# Data Centering
data = murugan.array([10, 20, 30, 40, 50])
mean = murugan.mean(data)
centered_data = data - mean
print('Centered data = ',centered_data)
# Standardization
std_dev = murugan.std(data)
standardized_data = (data - mean) / std_dev
print("standardized data = ",standardized_data)
# Log Transformation
log_transformed_data = murugan.log(data)
print("log_transformed_data = ",log_transformed_data)

Centered data =  [-20. -10.   0.  10.  20.]
standardized data =  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
log_transformed_data =  [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


# Random Sampling and Generation

In [128]:


# Simple Random Sampling Without replacement
data = murugan.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
random_samples = murugan.random.choice(data, size=5, replace=False)
random_samples

array([ 3,  1,  9,  8, 10])

In [129]:

# Bootstrap Sampling
num_samples = 1000
bootstrap_samples = murugan.random.choice(data, size=(num_samples, len(data)), replace=True)
bootstrap_samples

array([[ 5,  2,  9, ...,  5,  4,  6],
       [ 8,  8,  9, ..., 10,  3,  7],
       [ 9, 10,  5, ...,  3,  1,  6],
       ...,
       [ 9,  1,  6, ...,  9, 10,  1],
       [ 2,  1,  8, ...,  4,  1,  9],
       [ 6,  6,  5, ...,  6,  1,  2]])

*Generation*

In [130]:

murugan.random.randint(0,100)

85

In [131]:

# Generates 5 random values from a standard normal distribution

mean = 0
std_dev = 1
normal_values = murugan.random.normal(mean, std_dev, 5)
print(normal_values)

[ 1.07991929  1.53890167 -1.18390526  0.09302732 -2.06655575]


In [132]:

# Simulates 5 sets of 10 trials with a success probability of 0.5

n_trials = 10
probability = 0.5
binomial_values = murugan.random.binomial(n_trials, probability, 5)
print(binomial_values)

[4 5 4 5 5]


In [133]:

 # Generates 5 random values following a Poisson distribution with a rate of 2.5

rate = 2.5
poisson_values = murugan.random.poisson(rate, 5)
print(poisson_values)

[3 3 0 1 6]


In [134]:

# Generates 5 random values following an exponential distribution with a scale

scale_parameter = 0.5
exponential_values = murugan.random.exponential(scale_parameter, 5)
print(exponential_values)

[0.01190532 0.07220141 0.18054203 0.17538111 0.28290262]


In [135]:

# Generates 5 random values following a log-normal distribution

mean_of_log = 0
std_dev_of_log = 0.5
lognormal_values = murugan.random.lognormal(mean_of_log, std_dev_of_log, 5)
print(lognormal_values)

[1.60003334 0.5283503  0.70483087 0.9186408  1.52700595]


In [136]:

# Simulates 5 sets of 10 multinomial trials with the given probabilities

n_trials = 10
probabilities = [0.2, 0.3, 0.5] # Probabilities of each outcome
multinomial_values = murugan.random.multinomial(n_trials, probabilities, 5)
print(multinomial_values)

[[1 1 8]
 [4 2 4]
 [2 4 4]
 [3 1 6]
 [3 1 6]]


**7-Numpy for Linear Algebra**

# Complex Matrix Operations

In [137]:

A = murugan.array([[1, 2], [3, 4]])
# Calculate the inverse of A
A_inv = murugan.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [138]:

A = murugan.array([[2, -1], [1, 1]])
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = murugan.linalg.eig(A)
print("eigenvalues:",eigenvalues)
print("eigenvectors:",eigenvectors)

eigenvalues: [1.5+0.8660254j 1.5-0.8660254j]
eigenvectors: [[0.35355339+0.61237244j 0.35355339-0.61237244j]
 [0.70710678+0.j         0.70710678-0.j        ]]


In [139]:

A = murugan.array([[1, 2], [3, 4], [5, 6]])
# Compute the Singular Value Decomposition (SVD)
U, S, VT = murugan.linalg.svd(A)

# Solve Linear Equations

In [140]:

A = murugan.array([[2, 3], [4, 5]])

b = murugan.array([6, 7])
# Solve Ax = b for x
x = murugan.linalg.solve(A, b)
print(x)

[-4.5  5. ]


**8-Advanced Numpy Techniques**

# Masked Arrays



In [141]:

import numpy.ma as ma

# Temperature dataset with missing values (-999 represents missing values)
temperatures = murugan.array([22.5, 23.0, -999, 24.5, -999, 26.0, 27.2, -999, 28.5])
# Calculate the mean temperature without handling missing values
mean_temperature = murugan.mean(temperatures)
# Print the result = -316.14
print("Mean Temperature (without handling missing values):", mean_temperature)

# Create a mask for missing values (-999)
mask = (temperatures == -999)
# Create a masked array
masked_temperatures = ma.masked_array(temperatures, mask=mask)
# Calculate the mean temperature (excluding missing values)
mean_temperature = ma.mean(masked_temperatures)
# Print the result = 25.28
print("Mean Temperature (excluding missing values):", mean_temperature)

Mean Temperature (without handling missing values): -316.14444444444445
Mean Temperature (excluding missing values): 25.28333333333333


# Structured Arrays

In [142]:


# Define data types for fields

dt = murugan.dtype([('name', 'S20'), ('age', int), ('salary', float)])
# Create a structured array
employees = murugan.array([('Alice', 30, 50000.0), ('Bob', 25, 60000.0)], dtype=dt)
# Access the 'name' field of the first employee
print(employees['name'][0])
# Access the 'age' field of all employees
print(employees['age'])

b'Alice'
[30 25]
